In [1]:
import numpy as np

In [2]:
def randomization(n):
    """
    input is an integer n
    output is a randomly-generated nx1 Numpy array A
    """
    A = np.random.random(size=n).reshape(n, 1)
    return A

In [9]:
def operations(h, w):
    """
    inputs h and w, which are the hight and width of both arrays
    returns the two arrays A and B, and s which is the sum of them.
    
    """
    A = np.random.random(size=(h, w))
    B = np.random.random(size=(h, w))
    s = A + B
    return A, B, s

In [18]:
operations(3,4)

(array([[0.6656925 , 0.13649196, 0.65489915, 0.3461107 ],
        [0.12742844, 0.02810267, 0.47101862, 0.39858732],
        [0.35807723, 0.87083873, 0.619065  , 0.1143599 ]]),
 array([[0.47392049, 0.24146331, 0.04421492, 0.50092057],
        [0.3590518 , 0.30213765, 0.1039726 , 0.63243014],
        [0.15582796, 0.17966711, 0.34109521, 0.46818442]]),
 array([[1.13961299, 0.37795527, 0.69911407, 0.84703127],
        [0.48648025, 0.33024032, 0.57499123, 1.03101746],
        [0.51390519, 1.05050584, 0.96016021, 0.58254431]]))

In [11]:
def norm(A, B):
    """
    input is two Numpy column arrays A and B
    returns the L2 norm of their sum.
    
    """
    s = A + B
    return np.linalg.norm(s)

In [19]:
A = randomization(3)
B = randomization(3)
norm(A,B)

2.0548357128940546

In [20]:
def neural_network(inputs, weights):
    """
     input is vector (2x1 numpy array) that goes through a 1-layer neural network
     with a randomized weight (2x1 matrix numpy array) and one output (1x1 numpy array).

    """
    z = np.tanh(weights.T.dot(inputs))
    return z

In [21]:
inputs = randomization(4)
weights = randomization(4)
neural_network(inputs, weights)

array([[0.75591579]])

In [22]:
def scalar_function(x, y):

    if x<=y:
       return (np.dot(x,y))
    else:
       return(x/y)

In [23]:
scalar_function(4, 2)

2.0

In [26]:
def vector_function(x, y):
    vectorFunc = np.vectorize(scalar_function)
    return vectorFunc(x,y)

In [27]:
vector_function(4, 2)

array(2.)

In [28]:
scalar_function(2, 4)

8

In [29]:
vector_function(2, 4)

array(8)